import { Category } from "./categories";

export interface Product {
    id: number;
    name: string;
    price: number;
    description: string;
    rating: number;
    url: string;
    imgURL: string;
    link: string;
    category: Category;
    likes: number;
  };
  
  export const products: Product[] = [
    {
      id:1,
      name:"1025 Dokdo Toner",
      price: 4300,
      description: "Outstanding toner exfoliates dead skin cells and leaves skin replenished with long lasting moisture. Experience simple but exceptional skincare everyday.",
      rating: 5,
      url: "https://kaspi.kz/shop/p/round-lab-toner-1025-dokdo-toner-200-ml-104770477/?c=750000000:%20undefined",
      imgURL: "https://roundlab.com/cdn/shop/files/1025-dokdo-toner-round-lab-1_900x.jpg?v=1687196657",
      link: "https://web.telegram.org/k/#@ZhZhanelK",
      category: { name: "Косметика" },
      likes: 273,
    },
    {
      id: 2,
      name: "Apple Watch Series 8 45mm",
      price: 237618,
      description: "Смарт-часы Apple Watch Series 8 45 мм Aluminum черный",
      rating: 5,
      url: "https://kaspi.kz/shop/p/apple-watch-series-8-45-mm-aluminum-chernyi-106362847/?c=750000000#!/item",
      imgURL: "https://resources.cdn-kaspi.kz/shop/medias/sys_master/images/images/h0b/h04/63158967959582/apple-watch-series-8-41-mm-cernyj-106362847-1.jpg",
      link: "https://web.telegram.org/k/#@ZhZhanelK",
      category: { name: "Часы" },
      likes: 80,
    },
    {
      id: 3,
      name: "1025 Dokdo Cleanser",
      price: 6000,
      description: "Slightly acidic (pH 5.0 - 6.0), foamy and creamy cleanser purifies and removes excess sebum without over-drying. It clears away impurities and helps the skin maintain a healthy moisture balance.",
      rating: 5,
      url: "https://kaspi.kz/shop/p/round-lab-mjagkaja-penka-dlja-umyvanija-1025-dokdo-cleanser-penka-150-ml-115419628/?c=750000000",
      imgURL: "https://roundlab.com/cdn/shop/files/1025-dokdo-cleanser-round-lab-3.jpg?v=1687288383",
      link: "https://web.telegram.org/k/#@ZhZhanelK",
      category: { name: "Косметика" },
      likes: 1420,
    },
    {
      id: 4,
      name: "Xiaomi Mi Band 7",
      price: 21898,
      description: "«Умный» трекер ждали как пользователи прошлых версий девайса, так и те, кто впервые решился приобрести себе столь технологичное устройство.",
      rating: 5,
      url: "https://kaspi.kz/shop/p/xiaomi-mi-band-7-chernyi-105075100/?c=750000000#!/item",
      imgURL: "https://resources.cdn-kaspi.kz/shop/medias/sys_master/images/images/h76/h2e/51135083642910/xiaomi-mi-band-7-chernyi-105075100-1.jpg",
      link: "https://web.telegram.org/k/#@ZhZhanelK",
      category: { name: "Часы" },
      likes: 228,
    },
    {
      id: 5,
      name: "Birch Moisturizing Sheet Mask",
      price: 3000,
      description: "Ampoule in a mask - intensive moisture delivered through Birch Sap and Hyaluronic Acid. A great supply of hydration and moisture retention.",
      rating: 5,
      url: "https://kaspi.kz/shop/p/round-lab-tkanevaja-birch-juice-moisturizing-mask-25-ml-105258541/?c=750000000",
      imgURL: "https://roundlab.com/cdn/shop/files/birch-moisturizing-sheet-mask-round-lab-1_900x.png?v=1687196762",
      link: "https://web.telegram.org/k/#@ZhZhanelK",
      category: { name: "Косметика" },
      likes: 758,
    },
    {
      id: 6,
      name: "Samsung Galaxy Watch 4",
      price: 95977,
      description: "Умные часы Samsung - это не просто гаджет, а ваш верный спутник на пути к достижению задач и самосовершенствованию.",
      rating: 5,
      url: "https://kaspi.kz/shop/p/samsung-galaxy-watch-4-classic-sm-r890nzkacis-46-mm-chernyi-chernyi-102170938/?c=750000000#!/item",
      imgURL: "https://resources.cdn-kaspi.kz/shop/medias/sys_master/images/images/h31/h9b/62047597559838/samsung-galaxy-watch-4-classic-sm-r890-cernyj-102170938-1-Container.jpg",
      link: "https://web.telegram.org/k/#@ZhZhanelK",
      category: { name: "Часы" },
      likes: 240,
    },
    {
      id: 7,
      name: "Amazon Kindle Paperwhite 2021",
      price: 161000,
      description: "Электронная книга Amazon Kindle Paperwhite 2021.",
      rating: 5,
      url: "https://kaspi.kz/shop/p/amazon-kindle-paperwhite-2021-chernyi-102838488/?c=750000000#!/item",
      imgURL: "https://resources.cdn-kaspi.kz/shop/medias/sys_master/images/images/h6a/ha1/47093254455326/amazon-kindle-paper-2021-chernyi-102838488-1.jpg",
      link: "https://web.telegram.org/k/#@ZhZhanelK",
      category: { name: "Книга" },
      likes: 56,
    },
    {
      id: 8,
      name: "Apple AirPods Max",
      price: 365990,
      description: "Bluetooth гарнитура Apple AirPods Max сможет полностью изменить ваше представление о полноразмерных наушниках. Данная модель разработана с применением первоклассных материалов и передовых технологий.",
      rating: 5,
      url: "https://kaspi.kz/shop/p/apple-airpods-max-sinii-101180956/?c=750000000#!/item",
      imgURL: "https://resources.cdn-kaspi.kz/shop/medias/sys_master/images/images/h84/h0d/46659800498206/apple-airpods-max-sinij-101180956-1-Container.jpg",
      link: "https://web.telegram.org/k/#@ZhZhanelK",
      category: { name: "Наушники" },
      likes: 128,
    },
    {
      id: 10,
      name: "Kieslect K11",
      price: 24980,
      description: "Умные часы Kieslect K11 оснащены постоянно включенным полноэкранным сенсорным дисплеем с разрешением 1.39 Ultra Amoled.",
      rating: 5,
      url: "https://kaspi.kz/shop/p/kieslect-k11-chernyi-104947291/?c=750000000#!/item",
      imgURL: "https://resources.cdn-kaspi.kz/shop/medias/sys_master/images/images/h5c/h60/51661437468702/xiaomi-kieslect-k11-cernyj-104947291-1.jpg",
      link: "https://web.telegram.org/k/#@ZhZhanelK",
      category: { name: "Часы" },
      likes: 7,
    },
    {
      id: 11,
      name: "Birch Moisturizing Cream",
      price: 11000,
      description: "A gentle, well-rounded moisturizer for total moisture care and skin barrier strengthening.",
      rating: 5,
      url: "https://kaspi.kz/shop/p/round-lab-krem-birch-juice-moisturizing-cream-dlja-litsa-80-ml-105496795/?c=750000000",
      imgURL: "https://roundlab.com/cdn/shop/files/birch-moisturizing-cream-round-lab-1_900x.jpg?v=1687196692",
      link: "https://web.telegram.org/k/#@ZhZhanelK",
      category: { name: "Косметика" },
      likes: 10,
    },
    {
      id: 12,
      name: "Soybean Nourishing Cleansing Oil",
      price: 7500,
      description: "Crafted from a blend of natural oils such as avocado, grapeseed, evening primrose, and meadowfoam seed, this cleansing oil nurtures and cleanses, providing soothing comfort.",
      rating: 5,
      url: "https://kaspi.kz/shop/p/round-lab-soybean-cleansing-gidrofil-noe-maslo-200-ml-104228736/?c=750000000",
      imgURL: "https://roundlab.com/cdn/shop/files/80_900x.png?v=1702664340",
      link: "https://web.telegram.org/k/#@ZhZhanelK",
      category: { name: "Косметика" },
      likes: 1000,
    },
    {
      id: 13,
      name: "Amazfit Bip U Pro",
      price: 25368,
      description: "Безрамочный дизайн часов Amazfit Bip U Pro оборудованы экраном AMOLED с диагональю 1.43 дюйма и разрешением 320x302 пикселя, обеспечивающим превосходное визуальное отображение, благодаря которому все входящие звонки, сообщения и напоминания становятся предельно четкими.",
      rating: 5,
      url: "https://kaspi.kz/shop/p/amazfit-bip-u-pro-chernyi-100914321/?c=750000000#!/item",
      imgURL: "https://resources.cdn-kaspi.kz/shop/medias/sys_master/images/images/h8b/h68/33549396967454/amazfit-bip-u-pro-cernyj-100914321-1-Container.jpg",
      link: "https://web.telegram.org/k/#@ZhZhanelK",
      category: { name: "Часы" },
      likes: 30,
    },
    {
      id: 14,
      name: "Джордж Оруэлл 1984",
      price: 1984,
      description: "Культовый роман Джорджа Оруэлла в новом, полном, без цензуры и купюр, переводе Дарьи Целовальниковой. «1984» — одна из трех знаменитых антиутопий XX века.",
      rating: 5,
      url: "https://kaspi.kz/shop/p/oruell-dzh-1984-105221802/?c=750000000#!/item",
      imgURL: "https://resources.cdn-kaspi.kz/shop/medias/sys_master/images/images/hac/h57/51390686887966/oruell-dz-1984-105221802-1.jpg",
      link: "https://web.telegram.org/k/#@ZhZhanelK",
      category: { name: "Книга" },
      likes: 14,
    },
    {
      id: 15,
      name: "Пауло Коэльо Алхимик",
      price: 2539,
      description: "Алхимик — самый известный роман бразильского писателя Пауло Коэльо, любимая книга миллионов людей во всем мире. В юности люди не боятся мечтать, все кажется им возможным.",
      rating: 5,
      url: "https://kaspi.kz/shop/p/koel-o-p-alhimik-26018156/?c=750000000#!/item",
      imgURL: "https://resources.cdn-kaspi.kz/shop/medias/sys_master/images/images/hcd/h84/31576356913182/koel-o-p-alkhimik-26018156-1.jpg",
      link: "https://web.telegram.org/k/#@ZhZhanelK",
      category: { name: "Книга" },
      likes: 10,
    },
    {
      id: 16,
      name: "Айзексон Уолтер: Стив Джобс",
      price: 9126,
      description: "В основу этой биографии легли беседы с самим Стивом Джобсом, а также с его родственниками, друзьями, врагами, соперниками и коллегами.",
      rating: 5,
      url: "https://kaspi.kz/shop/p/aizekson-u-stiv-dzhobs-26006223/?c=750000000#!/item",
      imgURL: "https://resources.cdn-kaspi.kz/shop/medias/sys_master/images/images/h9e/hc8/31946560438302/ajzekson-u-stiv-dzobs-26006223-1.jpg",
      link: "https://web.telegram.org/k/#@ZhZhanelK",
      category: { name: "Книга" },
      likes: 8,
    },
    {
      id: 17,
      name: "Эрих Мария Ремарк: Триумфальная Арка",
      price: 2838,
      description: "«Триумфальная арка» – пронзительная история любви всему наперекор, любви, приносящей боль, но и дарующей бесконечную радость.",
      rating: 5,
      url: "https://kaspi.kz/shop/p/remark-e-m-triumfal-naja-arka-26025852/?c=750000000#!/item",
      imgURL: "https://resources.cdn-kaspi.kz/shop/medias/sys_master/images/images/h7e/hc1/31836880273438/remark-e-m-triumfalnaa-arka-26025852-1-Container.jpg",
      link: "https://web.telegram.org/k/#@ZhZhanelK",
      category: { name: "Книга" },
      likes: 7,
    },
    {
      id: 18,
      name: "Apple AirPods 3",
      price: 95675,
      description: "Динамический драйвер, разработанный Apple, использует специальный усилитель, обеспечивая невероятную детальность звучания.",
      rating: 5,
      url: "https://kaspi.kz/shop/p/apple-airpods-3-belyi-102667744/?c=750000000#!/item",
      imgURL: "https://resources.cdn-kaspi.kz/shop/medias/sys_master/images/images/hd3/h7b/46719105990686/apple-airpods-3-belyj-102667744-1.jpg",
      link: "https://web.telegram.org/k/#@ZhZhanelK",
      category: { name: "Наушники" },
      likes: 7,
    },
    {
      id: 19,
      name: "Apple AirPods",
      price: 68480,
      description: "AirPods настраиваются в одно касание. Автоматически включаются и устанавливают соединение. Пользоваться ими невероятно легко.",
      rating: 5,
      url: "https://kaspi.kz/shop/p/apple-airpods-with-charging-case-belyi-4804056/?c=750000000#!/item",
      imgURL: "https://resources.cdn-kaspi.kz/shop/medias/sys_master/images/images/h3c/h64/46637140475934/apple-airpods-2-with-charging-case-belyj-4804056-2-Container.jpg",
      link: "https://web.telegram.org/k/#@ZhZhanelK",
      category: { name: "Наушники" },
      likes: 11,
    },
    {
      id: 20,
      name: "Apple AirPods Pro",
      price: 103176,
      description: "AirPods Pro — уникальные наушники с технологией активного шумоподавления, которые непрерывно оптимизируют звучание с учётом формы вашего уха и положения вкладышей.",
      rating: 5,
      url: "https://kaspi.kz/shop/p/apple-airpods-pro-belyi-4804718/?c=750000000#!/item",
      imgURL: "https://resources.cdn-kaspi.kz/shop/medias/sys_master/images/images/h5e/hcc/46659804692510/apple-airpods-pro-belyj-4804718-1-Container.jpg",
      link: "https://web.telegram.org/k/#@ZhZhanelK",
      category: { name: "Наушники" },
      likes: 2,
    },
    {
      id: 21,
      name: "Apple EarPods",
      price: 12907,
      description: "В отличие от круглой формы обычных наушников-вкладышей, конструкция наушников EarPods продиктована геометрией ушной раковины.",
      rating: 5,
      url: "https://kaspi.kz/shop/p/apple-earpods-lightning-belyi-4801876/?c=750000000#!/item",
      imgURL: "https://resources.cdn-kaspi.kz/shop/medias/sys_master/images/images/h29/ha8/31582164779038/apple-earpods-lightning-belyj-4801876-1-Container.jpg",
      link: "https://web.telegram.org/k/#@ZhZhanelK",
      category: { name: "Наушники" },
      likes: 77,
    }
  ];
  
  
  /*
  Copyright Google LLC. All Rights Reserved.
  Use of this source code is governed by an MIT-style license that
  can be found in the LICENSE file at https://angular.io/license
  */